server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /**

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      location:
      file-size-threshold: 0
      max-file-size: 10MB



# MyBatis
mybatis:
  type-aliases-package: cn.com.exam.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


#Redis
redis:
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器端口号
  port: 6379
  # 使用的数据库索引，默认是0
  database: 0
  # 连接超时时间
  timeout: 1800000
  # 设置密码
  password:
  lettuce:
    pool:
      # 最大阻塞等待时间，负数表示没有限制
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 5
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中最大连接数，负数表示没有限制
      max-active: 20

logging:
  level:
    cn.com.exam.dao: debug
  config:
    classpath: log4j.xml


